### ISSUE TITLE
フォームから入力された値をechoで表示してみましょう。

### ISSUE THREAD

**Issue by saitos01** [yousuketanaka/phptraining#2]
#1 はすぐ終わると思いますので 続けてこちらもやってみましょう。
- 「HTMLのフォームを作成」して
- 「フォームから送信した情報をechoで画面に表示」

してみましょう。

難しい場合は「HTML フォーム」から調べてみるといいでしょう(すでに学ばれているのでこちらもすぐかもしれませんね)。

**Comment by yousuketanaka** [comment]
承知しました。

**Comment by yousuketanaka** [comment]
作成したファイルをgitにプッシュする際に以下の添付の表示が出てきました。これを解決するために幾つかのサイトで調べて試したのですが、上手くいきません。確認するキーワードはありますでしょうか？
https://www.evernote.com/l/ARs86lEroTdDXb-CSZLExbo2e4IDnG5gCCk

**Comment by saitos01** [comment]
@yousuketanaka 「出力を開く」を押すと何が表示されますでしょうか？

**Comment by saitos01** [comment]
@yousuketanaka
また、これらの単語の中で意味のわからない言葉はありますでしょうか？
- リポジトリ
- リモート・リポジトリ
- ローカル・リポジトリ
- マージ (ブランチをやっていないので少し難しいかもしれません。)
- コミット

追記: 現状なんとなく頭の中でイメージできていたらOKです。 これらの言葉を知ることで解決に近づけると思っています。

**Comment by yousuketanaka** [comment]
> 「出力を開く」を押すと何が表示されますでしょうか？

特に何も表示はされません。「出力」箇所が表示されるだけになっています。
https://www.evernote.com/l/ARtqUdxy4gtCIYqqp_ZIQu_90dqU9jFQyG4

**Comment by saitos01** [comment]
@yousuketanaka 
ありがとうございます。
以下の内容に対して指示が足りなかったため補足させてください。

```
また、これらの単語の中で意味のわからない言葉はありますでしょうか？

リポジトリ
リモート・リポジトリ
ローカル・リポジトリ
マージ (ブランチをやっていないので少し難しいかもしれません。)
コミット
追記: 現状なんとなく頭の中でイメージできていたらOKです。 これらの言葉を知ることで解決に近づけると思っています。

```

補足：以上の言葉の中でわからない言葉があれば教えてください。またそれらの言葉を調べてみましょう。

**Comment by saitos01** [comment]
@yousuketanaka 

1、今どのような問題が起きているのかを把握する。ー今ここを進めています。

2、問題の解決方法を探す。ー Next

1が終わったとき、または詰まったときは報告・相談くださいませ。

**Comment by yousuketanaka** [comment]
上記の単語は以下のように理解しています。

> リポジトリ

作業スペース。この中でファイルを追加し、情報の追加、更新、削除を行う。

> リモート・リポジトリ

git内に作成された作業スペース。ローカルから送り出す情報の宛先となる。

> ローカル・ディポジトリ

送り元の作業スペース。PC内の作業スペースであり、制作のほとんどはここで行い、最終的にはリモート・リポジトリにプッシュして複数の開発者が閲覧、作業ができるようになる。

> マージ

質問されるまでこれはわかりませんでした。調べたところ、複数のコミットを統合することの意味でした。複数人での開発を前提として使われる言葉と理解しています。

> コミット

以下の図のように理解しています。つまり、一度ローカルレポジトリにgitへアクセスすることを宣言し（イメージ）、その後、実際にアクセスして情報をgitにアップするという理解です。

https://www.evernote.com/l/ARujU6oVPcdJJqePGddJPLzpAIotwDvRH3I

**Comment by saitos01** [comment]
@yousuketanaka 

> リポジトリ
- 田中さんのご理解で合っております。

> リモート・リポジトリ
- ご理解で合っております。現状ですと、いただいたイメージ内のどこにあたりますでしょうか。

https://www.evernote.com/l/ARujU6oVPcdJJqePGddJPLzpAIotwDvRH3I

> ローカル・ディポジトリ
- ご理解で合っております。

> マージ
- ご理解でほぼ合っております。現状は「反映・統合」のような言葉と同じ意味と思ってもらって構いません。今後ブランチを学ぶとより理解が深まると思います。

> コミット
> 
> つまり、一度ローカルレポジトリにgitへアクセスすることを宣言し（イメージ）、その後、実際にアクセスして情報をgitにアップするという理解です。

ここでいう
- 「gitへアクセスすることを宣言」
  -「実際にアクセスして情報をgitにアップする」
  という表現はいただいたイメージでいうとどこの状態(コミット・プッシュなど)での話にあたりますでしょうか(あるいはイメージには表現されていないものを示されていますでしょうか)。

https://www.evernote.com/l/ARujU6oVPcdJJqePGddJPLzpAIotwDvRH3I

**Comment by yousuketanaka** [comment]
> ご理解で合っております。現状ですと、いただいたイメージ内のどこにあたりますでしょうか。

githubリポジトリがリモートリポジトリという理解でおります。

> 「gitへアクセスすることを宣言」 -「実際にアクセスして情報をgitにアップする」 という表現はいただいたイメージでいうとどこの状態(コミット・プッシュなど)での話にあたりますでしょうか(あるいはイメージには表現されていないものを示されていますでしょうか)。

「gitへアクセスすることを宣言」=コミット、
「実際にアクセスして情報をgitにアップする」=プッシュ
と理解しており、上記の2つの表現は、イメージで表現されていないものは含んでいないという理解です。

**Comment by saitos01** [comment]
@yousuketanaka 

> githubリポジトリがリモートリポジトリという理解でおります。

その理解で合っております。

> 「gitへアクセスすることを宣言」= コミット
> 「実際にアクセスして情報をgitにアップする」=プッシュ

言葉のニュアンスの違いだけかもしれませんが、一度コミットとプッシュについて調べてみましょう。

**Comment by yousuketanaka** [comment]
Netbeansの使い方について確認させてください。外部のcssやjsのファイルを取り込みたいと考え、その方法を探していたのですが、あまりに簡単なのかその方法を見つけることができませんでした。ですが、MAMPのhtdocsに直接ファイルを持っていくとNetbeansにも反映されました。これはこの方法しかないのでしょうか？

**Comment by saitos01** [comment]
Netbeansの使い方に対しての答えにはならないのですが

「外部スタイルシート」「JavaScript 外部」で検索してみましょう。

こちらはNetbeansに限らず、一般的な(開発環境は問わない)外部ファイルの参照の仕方になります。

「外部」「取り込む」の解釈にずれがありましたら指摘してくださいませ。

**Comment by yousuketanaka** [comment]
キーワードの提供ありがとうございます。早速調べます。

**Comment by saitos01** [comment]
申し訳ありません。
「外部」「取り込む」に関して解釈のずれがありそうなので、一旦こちらで調べてから再度返信いたします。

**Comment by yousuketanaka** [comment]
承知しました。返信は明日で結構です。

**Comment by saitos01** [comment]
回答修正します。
NetBeansの外部のCSSやJsの取り込みについて、もしドラック&ドロップでできないようでしたら、直接MAMPのhtdocsに置くやり方で大丈夫だと思います。

**Comment by saitos01** [comment]
gitプッシュ時のエラーについて、コミットとプッシュについて調べたあとも解決に時間がかかりそうであればこちらを見てくださいませ。

https://github.com/yousuketanaka/phptraining/issues/6

**Comment by yousuketanaka** [comment]
> 言葉のニュアンスの違いだけかもしれませんが、一度コミットとプッシュについて調べてみましょう。

調べた結果、私は以下のように理解しました。
🔹コミット
ファイルやディレクトリの追加・変更を、ローカルリポジトリに記録する操作。複数のサイトの説明では、単に「リポジトリに記録する」と説明されていましたが、リモートリポジトリに記録する操作は「プッシュ」であるため、特に「ローカルリポジトリ」への記録操作をコミットと言うと理解しています。

🔹プッシュ
ローカルリポジトリ内の変更履歴をリポートリポジトリにアップロードする作業。

**Comment by saitos01** [comment]
コミット、プッシュともに理解もばっちりですね！

コミットに関して現状の田中さんの環境では、

> ファイルやディレクトリの追加・変更を、ローカルリポジトリに記録する操作。

で全く問題ありません。

コミットの例外として今回のエラーの原因になった「GitHubへの直接コミット」のように単に「リポジトリに記録する」と理解されていたほうが柔軟にイメージできる場合もあります。覚えておいてくださいませ。

**Comment by yousuketanaka** [comment]
承知しました。報告が遅れましたが、formの作成とその出力の作成を完了しております。

**Comment by saitos01** [comment]
了解しました。確認いたします！

**Comment by saitos01** [comment]
本issueの課題のFormのコードもGoodでした！

質問などなければcloseしたいと思いますー。

**Comment by saitos01** [comment]
Closeしますね。
