### ISSUE TITLE
DBへの接続の準備をしよう。DBが何かまずは調べてみましょう。

### ISSUE THREAD

**Issue by saitos01** [yousuketanaka/phptraining#3]
こちらのMAMPでの環境構築が前提となります。先に以下のIssueに取り掛かりましょう。

https://github.com/yousuketanaka/phptraining/issues/4

調べるタスクになります。
データベースの扱いについて調査しましょう。

「MySQL（データベース）とはなんなのか」を調べてみましょう。 

MySQLというデータベースがMAMPで利用されているのでこれを使います。 
MAMP には phpMyAdminというMySQLを扱うためのツールが入っています。これの使い方を調べます。 
- phpMyAdminでデータベースを作成するにはどうしたら良いか 
- phpMyAdminでデータベースにテーブルを作成するにはどうしたら良いか 
- phpMyAdminでテーブルにカラムを追加するにはどうした良いか 

dotinstallなどを利用してMySQLについて学んでみるのも良いと思います。 
「phpMyAdminで」としているのはツールを使う方が簡単だからなので、もしも黒い画面を使ってコマンドラインで扱うのがわかりやすそうならその方法でも構いません。 

まず一回自力で調査をしてみるのが大事なので、やってみましょう。

調べてみてできそうであれば手を動かしてみましょう。

**Comment by yousuketanaka** [comment]
承知しました。

**Comment by yousuketanaka** [comment]
🔹MySQL（データベース）とは何か?

・オープンソースで、世界で最もシェアがあるデータベース。
・リレーショナル型のデータベース(複数の表データを結合して使うことができる)
・シンプルで速く、PHPなどとの相性が良い

**Comment by yousuketanaka** [comment]
ターミナルではなく、phpmyadminで作成してみました。

🔹phpMyAdminでデータベースを作成するにはどうしたら良いか?

https://www.evernote.com/l/ARs594vUd4FDObR9kihSYnbG-TUEspITD0k
　
🔹phpMyAdminでデータベースにテーブルを作成するにはどうしたら良いか?

https://www.evernote.com/l/ARubo-Hk5xJOsIkdWvWlLi1k4VXeFpHSbko

🔹phpMyAdminでテーブルにカラムを追加するにはどうした良いか?

https://www.evernote.com/l/ARtIM-_ldttE64CwMFEDXnuDwfedXXVb908

**Comment by saitos01** [comment]
phpmyadminでの

データベース作成ー＞テーブル作成ー＞カラムの追加

の基本的な流れはおさえられていますね！

以下少し細かい点ですが補足させてください。

### 補足

https://www.evernote.com/shard/s283/sh/39f78bd4-7781-4339-b47d-9228526276c6/f93504b292130f49

最近（MySQL 5.5.3以降）は照合順序として「utf8mb4_general_ci」を使うケースが増えてきています。
これは絵文字の文字化けを防ぐためです。

http://wiki.onakasuita.org/pukiwiki/?utf8mb4_general_ci

https://www.evernote.com/shard/s283/sh/9ba3e1e4-e712-4eb0-891d-5af5a52e2d64/e155de1691d26e4a

今後フレームワークを使うことを考えても、テーブル名は複数系にする習慣をつけておくと良いと思います。

http://qiita.com/SiriusArc7/items/72da4ec221211d0b8334

https://www.evernote.com/shard/s283/sh/4833efe5-76db-44eb-80b0-3051035e7b83/c1f79d5d755bf74f

のカラムの名前の欄(カラム名と呼ばれます)は「日本語」よりも「英数字」を使うほうが一般的です。

http://oshiete.goo.ne.jp/qa/8661826.html

varcharのカラムにも念のため照合順序（utf8mb4_general_ci）をつけましょう。

また、テーブルのカラムとして作成日時をあらわす「created_at」と更新日時をあらわす「updated_at」というカラムをよく使います。
これらのカラムも習慣として追加しましょう。

補足以上になります。

画像とてもわかりやすくコミュニケーションしやすいです。ありがとうございます。

**Comment by yousuketanaka** [comment]
理解を確認させてください。以下の疑問に答えるべく、幾つか調べて自分の理解を得ました。その理解の確認をさせてください。

疑問:「phpmyadminでは、ターミナルを使うより簡単にデータベースの構築が可能となっている。ここでターミナルを使う意義は何か? （ネット上にもターミナルの使い方、データの「更新」、「選択」、「追加」、「削除」方法が詳しく説明してあり、学習を迫られている印象を受ける」）

理解:特にターミナルに大きな意義があるわけではない。どちらを使っても良い。初心者はphpmyadminから直接sql文を打ち込んだ方がわかりやすいが、慣れてくると、ターミナルで直接作業した方が作業効率がアップする。

**Comment by yousuketanaka** [comment]
> 最近（MySQL 5.5.3以降）は照合順序として「utf8mb4_general_ci」を使うケースが増えてきています。これは絵文字の文字化けを防ぐためです。

上記、承知しました。

> テーブル名は複数系にする習慣をつけておくと良いと思います。

上記承知しました。

> カラムの名前の欄(カラム名と呼ばれます)は「日本語」よりも「英数字」を使うほうが一般的です。

上記承知しました。

> varcharのカラムにも念のため照合順序（utf8mb4_general_ci）をつけましょう。

上記承知しました。

> テーブルのカラムとして作成日時をあらわす「created_at」と更新日時をあらわす「updated_at」というカラムをよく使います。これらのカラムも習慣として追加しましょう。

上記承知しました。

**Comment by saitos01** [comment]
> どちらを使っても良い。初心者はphpmyadminから直接sql文を打ち込んだ方がわかりやすいが、慣れてくると、ターミナルで直接作業した方が作業効率がアップする。

この部分の理解合っております。また、phpMyAdminはsql文を記述することなくMySQLのデータベースに対して様々な操作が可能というのも初心者にとってわかりやすい点だと思います。

「コマンドラインを使う意義」に関して追加として以下のことがあると思います。

### 「コマンドラインを使う意義」

phpMyAdminが使えない環境(あるいは環境を構築するのが面倒な場合)がある。ウェブブラウザが使えないということも環境によってはありえます。

よって、

#### ① phpMyAdminが使えるかつコマンドラインが使える環境
- 作業する人にとって作業効率の良い方を選んで使用する。

#### ② phpMyAdminが使えないがコマンドラインは使える環境
- コマンドラインを使う(しかない)。

ということになります。ターミナルではなくコマンドラインという言葉を使ったのは、ターミナルというのはMacからコマンドラインを入力するためのツールなので、ターミナル= Macの環境=①の環境ということになるからです。

また、phpMyAdminはMySQL用のツールなので他のデータベース管理システムでは使うことができないということもあります。さらに、Wikiのセキュリティ欄にも書いてありますが、セキュリティホールになることがあるので、phpMyAdminを本番のWebサーバに置くのを嫌がるケースが多いです(細かい点なので、そうなんだ程度の理解で大丈夫です)。置かない場合は②の環境になります。

https://ja.wikipedia.org/wiki/PhpMyAdmin

**Comment by yousuketanaka** [comment]
確認させてください。せっかく教えていただいたので、作成日時をあらわす「created_at」と更新日時をあらわす「updated_at」というカラムでデータベースを修正していました。

その際、データ型をどうするかという疑問に当たりました。
確認したところ、時間に対するデータ型は主に以下の5種類でした。
①date型('YYYY-MM-DD'が基本となる)
②datetime型('YYYY-MM-DD HH:MM:SS'が基本となる)
③timestamp型('YYYY-MM-DD HH:MM:SS'が基本となる)
④time型('HH:MM:SS'が基本となる)
⑤year(YYYY が基本となる)

このうち、②と③の使用上の明確な違いが理解できません。表示の違いは以下のURLで説明されています。(http://qiita.com/ykawakami/items/2449a24e3b82ff0cbab6)

表示が違うのであれば、あとはどの表示を好むかの趣向の違いと受け取るのですが、この理解であっていますでしょうか?

**Comment by yousuketanaka** [comment]
> varcharのカラムにも念のため照合順序（utf8mb4_general_ci）をつけましょう。

文字列に関するデータ型全てに当てはまると理解していますが、この理解でよろしいでしょうか？
すなわち、varcharだけでなくtext（長い文字列)やcharにも当てはまる、という理解です。

**Comment by saitos01** [comment]
datetimeとtimestampの明確な違いについて

https://dev.mysql.com/doc/refman/5.6/ja/datetime.html

をみてみると、
- 取り得る値の範囲が違う

DATETIME 値の範囲は '1000-01-01 00:00:00.000000' から '9999-12-31 23:59:59.999999'

TIMESTAMP 値の範囲は '1970-01-01 00:00:01.000000' から '2038-01-19 03:14:07.999999' 

ということになっていまして、2038年問題

https://ja.wikipedia.org/wiki/2038%E5%B9%B4%E5%95%8F%E9%A1%8C

を考えると「created_at」「updated_at」は`datetime` 型が良いと思われます。

参考URL

https://dev.mysql.com/doc/refman/5.6/ja/timestamp-initialization.html
https://dev.mysql.com/doc/refman/5.6/ja/datetime.html

**Comment by saitos01** [comment]
> 文字列に関するデータ型全てに当てはまると理解していますが、この理解でよろしいでしょうか？
> すなわち、varcharだけでなくtext（長い文字列)やcharにも当てはまる、という理解です。

はい、当てはまります。

「念のため」といったのは
指定しなかった場合データベースの照合順序が適用されるからです(今回ですと `utf8mb4_general_ci` )。

**Comment by saitos01** [comment]
こちらのIssueも問題なければcloseしますね。

**Comment by yousuketanaka** [comment]
返信が遅れて申し訳有りません。承知しました。よろしくお願いいたいsます。

**Comment by saitos01** [comment]
ご返信ありがとうございます。Closeいたします
