### ISSUE TITLE
DBへの接続の準備をしよう。DBを扱える環境を構築しよう。

### ISSUE THREAD

**Issue by saitos01** [yousuketanaka/phptraining#4]
MAMPをインストールしてみましょう。

MAMPに関しては様々な資料が存在しているので、まずは調べて進めてみてください。

環境構築ですので、どうしても詰まるところは出てくると思います。

その場合は相談してくださいませ。

**Comment by yousuketanaka** [comment]
承知しました。MAMPのインストールは完了しています。ここでは、インストールそのものの作業よりもMAMPについての理解を深めることが目的という理解でよろしいでしょうか？

**Comment by saitos01** [comment]
こちらのIssueはMAMPのインストールがゴールで大丈夫です！
Issueが全て終わり時間が余った場合は「LAMP」というワードを調べてみましょう。

**Comment by yousuketanaka** [comment]
承知しました。LAMPを調べます。

**Comment by yousuketanaka** [comment]
🔹「LAMP」というワードを調べてみましょう。
PHPを動かせる環境をLAMPと言っているようです。

L=Linux=OS
A=Apache=Webサーバー
M=MySQL=データベース管理システムのソフトウェア
P=PHP・Perl・Python=動的Webページを表示させるためのコンピューター・プログラミング言語

各要素は、データベース連動型のWebサイトを展開・構築するための技術の組み合わせのようです。これがMacの場合は、MAMPとなるという理解です。

**Comment by saitos01** [comment]
ばっちりですね！

> これがMacの場合は、MAMPとなるという理解です。

ここのご理解もGoodです！

**Comment by saitos01** [comment]
こちらcloseします。
