### ISSUE TITLE
DBへの接続の準備をしよう。SQLを使って値を入れてみましょう。

### ISSUE THREAD

**Issue by saitos01** [yousuketanaka/phptraining#5]
MAMPのPHPMyadminから直接SQL文を入れることでデータを操作します。

https://github.com/yousuketanaka/phptraining/issues/3

で作成したテーブルに実際にデータを1件以上入れてみましょう。

まずはSQL文について調べてみましょう。
- データを挿入するSQL文を調べてみましょう。

次にPHPMyadminに直接SQL文を入れる方法を調べて、1件以上データを挿入してみましょう。

**Comment by saitos01** [comment]
終わって時間が余った場合は、SQL文を使ったデータの「検索」「更新」「削除」も併せてやってみましょう。こちらに関しては現状できるところまでで大丈夫です（今後やっていきます）。

**Comment by yousuketanaka** [comment]
承知しました。やってみます。

**Comment by yousuketanaka** [comment]
> 作成したテーブルに実際にデータを1件以上入れてみましょう。データを挿入するSQL文を調べてみましょう。

以下のように作成してみました。

https://www.evernote.com/l/ARsxfnFDLC1Llo91UHkKmwrUHai5eSFt7nI

**Comment by saitos01** [comment]
画像ありがとうございます。

データのINSERTできていますね！

一つ追加として、「AUTO_INCREMENT」を調べてみましょう。

「AUTO_INCREMENT」を調べたあとに、画像内のINSERT文を(一部)書き換えてみましょう。

**Comment by yousuketanaka** [comment]
承知しました。まず、「AUTO_INCREMENT」を調べてみます。

**Comment by yousuketanaka** [comment]
🔹「AUTO_INCREMENT」
・テーブルにおいて、自動的に連番を割り振りたいときに設定するもの。
・AUTO_INCREMENTのid列には、1、2、3…と自動で割り振られるので、
　敢えて、idを指定する必要はない。（今回はここが誤っていたということですね。）
・消されたレコードは欠番としてそのままで、最後の一番大きい値に続けてレコードが作られていく。
・連番は好きな数値から始めることもできる。100を指定すれば、その次は101となる。

**Comment by saitos01** [comment]
> 敢えて、idを指定する必要はない。（今回はここが誤っていたということですね。）

ポイント押さえられたようで、よかったです。「AUTO_INCREMENT」の解釈あっております。

**Comment by yousuketanaka** [comment]
> 「AUTO_INCREMENT」を調べたあとに、画像内のINSERT文を(一部)書き換えてみましょう。

以下のように書き換えました。ただ、「AUTO_INCREMENT」と更新の関係が分からなかったのですが
特に、今回関係はないという認識でよろしいでしょうか?

https://www.evernote.com/l/ARsFDxhOX_pGsp3Lki1cZtG2-I6_BVG3F5w

**Comment by yousuketanaka** [comment]
次の練習として、「検索」、「削除」もやってみます。特に「検索」は初めてですので、どうするか学びたいと思います。

**Comment by saitos01** [comment]
画像内のINSERT文の画像はこちらを指しておりました。

https://www.evernote.com/l/ARsxfnFDLC1Llo91UHkKmwrUHai5eSFt7nI

ですので、

> 特に、今回関係はないという認識でよろしいでしょうか?

この認識であっております。

> 次の練習として、「検索」、「削除」もやってみます。特に「検索」は初めてですので、どうするか学びたいと思います。

お、いいですね！よろしくお願いします。

**Comment by yousuketanaka** [comment]
「削除」、「検索」を練習して、最低以下は使えるようにしました。漏れがありましたらご指摘ください。

以下、使えるようにしたsql分を記載します。今回は、table名をinqiriesとしてます。（本当はinquiries)
🔹「削除」
Delete from table名 WHERE id = 1;(id1のデータを削除)

🔹「AND」、「OR」
select id, name, furigana, prefecture from inqiries where id =1 AND id =2;(id1とid2を選択する)
select id, name, furigana, prefecture from inqiries where id =1 OR id =2;(id1かid2を選択する)

🔹文字列の部分一致検索 (LIKE)
select id, name from inqiries where name like '田中%';(前方一致)
select id, name from inqiries where name like '%中%';(中間一致)
select id, name from inqiries where name like '%田中';(後方一致)

🔹データの並べ替え(ORDER BY/ASC, DESC)
select id, name from inqiries order by id asc;(小さいもの順)
select id, name from inqiries order by  id desc;(大きいもの順)

🔹その他の検索条件（ IN / BETWEEN / DISTINCT / LIMIT ）
select id, name from inqiries where id in(1,3,5);(1と3と5のidのつく名前を同時に選択)
select id, name from inqiries where id between 1 and 6;(1から6までのidのつく名前を選択)
select distinct name from inqiries;(重複する名前を排除して、重複なく表示)
select id, name from inqiries limit 5; (上から5つを限定して表示)

🔹複合条件検索
select \* from inqiries where id between 2 and 6 order by id desc limit 3;(idが2から6までの間で、大きいものから3つだけ選択)

**Comment by yousuketanaka** [comment]
少し頭が混乱したため、phpmyadmin/mysql/sql文/の違いをまとめてみました。理解は正しいでしょうか?誤っていればご指摘ください。

mysql・・・・・・オープンソースのRDBMS（リレーショナル・データベース・マネジメント・システム）の一つで、要はデターベースの種類。他に比較対象としてOracleやAccessなどがある。上記のsql文は、他のDBでも使用できるが、mysqlでも当然使用できる。

phpmyadmin・・・上記のデータベースを扱う管理ツール

sql文・・・・・・データベースへアクセスするための言語

これはgitとgithubの関係似ていて、上記の各関係を以下のように理解しています。

①gitは複数の人間が同時に自分のPCにデータを複製し、更新したデータをプッシュすることで元のデータに反映することができる分散型のバージョン管理システム。
（これが、mysqlであり、RDBMSの典型）

②GithubはこのGitの仕組みを利用して、世界中の人が自分の作品を保存、公開できるようにしたウェブサービス。
（これがphpmyadminであり、mysqlのシステムを使ったサービス）

③sql文は、mysqlで使われるデータベースを操作する言語

**Comment by saitos01** [comment]
phpmyadmin/mysql/sql文 の理解合っております。

mysqlは狭義のデータベースと言えますね。広義は「検索や蓄積が容易にできるよう整理された情報の集まり」となります。

gitとGitHubの関係と完全に置き換えられるとは言い切れませんが、田中さんが似ていると考えている点は合っていると思います。

**Comment by saitos01** [comment]
「削除」、「検索」を練習ばっちりです！

**Comment by saitos01** [comment]
こちらCloseいたします。
