### ISSUE TITLE
Gitの問題について

### ISSUE THREAD

**Issue by saitos01** [yousuketanaka/phptraining#6]
田中さんのGitのプッシュの失敗についてこちらとしては以下が原因だと考えております。

もし「コミット」「プッシュ」について調べた後に解決に時間がかかりそうであればこちらを参照くださいませ。

> リモート・リポジトリにはローカル分岐にマージされていないコミットが含まれます。

リモート・リポジトリには(= GitHubには)
ローカル分岐に(= ローカルのmasterブランチに)
マージされていない(= 反映されていない)
コミットが含まれます(コミット履歴が含まれます)。

要約しますとGitHub(リモートリポジトリ)のコミットのほうが進んでいます。ということだと思います。

Pushの際にローカルよりリモートリポジトリの(同じブランチの)コミットが進んでいると今回のようなエラーがでます。
「リモートリポジトリにローカルの履歴を反映したいけど、ローカル・リモートどちらの履歴が正しいのか判断できない」みたいな状態だと思います。
### 解決策

上記あくまで予想になりますが、解決策は以下となります。

Pull (コマンドでいうと `git pull origin master` ) でリモートリポジトリのコミットをローカルに反映させます。

その状態で再度 PushするとうまくPushできるのではと思います。
### 問題が解決しなかった場合

もし問題が解決しなかった場合は再度相談くださいませ。
#2　のソースコードはコメント欄に貼り付ける（あるいは直接GitHubにアップロード）していただけると助かります。

Issueは先に進んでいただいて構いません。

以上です。よろしくお願いします。

**Comment by yousuketanaka** [comment]
上記の助言により、ようやく問題が解決しました。今後、同じ問題が起きれば、同じように解決できそうです。以下が解決方法。
https://www.evernote.com/l/ARsRAA1XXhZH-ZOdVQVcuDl_O6lEdJ9V5z0

**Comment by saitos01** [comment]
おお、解決できたようでなによりです。

> 今後、同じ問題が起きれば、同じように解決できそうです。

ここがとても素晴らしいですね！

**Comment by saitos01** [comment]
Issue内容終わったのでcloseしました。終わったIssueはこちら側でcloseしていきますね。

**Comment by yousuketanaka** [comment]
斎藤様。

closeの件、承知しました。
よろしくお願いいたします。

田中

2016-07-04 17:19 GMT+09:00 shoheis notifications@github.com:

> Issue内容終わったのでcloseしました。終わったIssueはこちら側でcloseしていきますね。
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/yousuketanaka/phptraining/issues/6#issuecomment-230232503,
> or mute the thread
> https://github.com/notifications/unsubscribe/ANs8HOh8t9t4kxXpERVindNY_bpdZtibks5qSMIQgaJpZM4JDtol
> .

## 

---

CLASS ACT Co.,Ltd
Yousuke Tanaka(Mr)
田中 陽介

Tel:       095998045
E-Mail: yousuketanaka11@gmail.com
Address:＃195, St.63, Boeng Keng Kang 1, Phnom Penh

---
