### ISSUE TITLE
Sourcetree をインストールして、GitHubにPushしてみましょう。

### ISSUE THREAD

**Issue by saitos01** [yousuketanaka/phptraining#7]
ソースコードの共有をスムーズにするためにこちら優先的に進めてくださると嬉しいです。

SourceTreeを導入してみましょう。

SourceTree は Git のリポジトリを視覚化することで管理・操作を簡単にするアプリケーションです。
### インストールと初期設定

まずはインストールして初期設定をしてみましょう。

https://ja.atlassian.com/software/sourcetree

インストールからの設定の手順に関しては、SourceTree のUIがよく更新されるため良い資料が見つけにくかもしれません。
以下URLは最近の記事なのでUIが近いものなのではないかと思います。

注意点：以下ページ内の「Connect an account」のところで「GitHub」を選択してください。

http://tyoshikawa1106.hatenablog.com/entry/2016/04/03/193340
- リポジトリを追加しましょう。

今回は、すでにあるリポジトリを追加するので、「新規リポジトリ」から「既存のローカルリポジトリを追加」を選択して、「phptraining」のリポジトリを選択して追加しましょう。
### CommitとPushをしてみましょう。
- ローカルで何かファイルを変更してコミットしてみましょう。
- 変更したコミットをGitHubの「phptraining」にPushしてみましょう。
- Pushする際にGitHub(リモート)のリポジトリをPush先として設定に追加する必要があります。以下のURLが参考になると思います。

注意点：リモート名は(任意なのですが) 「origin」 とする習慣があります。ホストタイプはGitHubにしてください。URL/パスはGitHub(リポジトリのトップページのClone or Downloadから取得できます)からコピペしてください。で「@git」ではじまるアドレスでうまくいかなければひとまず「https」ではじまるURLを使ってください。

http://personal-studio9.com/sourcetree_push/

何かわからないこと、不具合あれば相談くださいませ。

**Comment by yousuketanaka** [comment]
source treeの設定は完了しました。まだ不慣で、機能操作に慣れていませんが、昨日まで学んできたcommitとpushを行いました。結果、以下のような表示になりました。

https://www.evernote.com/l/ARtJIen5vm1AOaEyYgsgax4TUnY-AOMC5Gg

参考サイト
http://qiita.com/takamichi_tsutsumi/items/6358a74a62d4fc15d1a5
http://itstudio.co/2015/12/08/5158/

**Comment by saitos01** [comment]
画像と説明ありがとうございます。

インストールうまくいったようでよかったです。

いただいた画像から判断ができないため質問させてください。

Pushはどこのリモートリポジトリにされましたでしょうか?

**Comment by yousuketanaka** [comment]
> Pushはどこのリモートリポジトリにされましたでしょうか?

確かに、この質問が来て改めて考えたのですが、source treeのボタンを押してプッシュした結果、
source tree画面の右下に更新されたコードが現れたので、それで良しとしていましたが、これで
手続きが終了したということではないということですね。再度、手続きを確認してみます。

**Comment by saitos01** [comment]
お願いいたします！
目標としましてはPush後にこちらのGitHubのリポジトリ「phptraining」に変更が反映されていることです。

**Comment by yousuketanaka** [comment]
承知しました。

**Comment by yousuketanaka** [comment]
> 目標としましてはPush後にこちらのGitHubのリポジトリ「phptraining」に変更が反映されていることです。

以下のようなやり方で、「phptraining」に変更を反映させています。

https://www.evernote.com/l/ARuAJXQUestI46E2yPNdXd_poRpGSk4CIhQ

https://www.evernote.com/l/ARt_CVZe4cFEz6FEwzBbO_E7XdaHtWSieAY

https://www.evernote.com/l/ARvm6m5grUhDc56Yov7mRVLKAOglr9n-qvM

https://www.evernote.com/l/ARvUGyrOscBJzpdjMMZOq19TisPwpwTRZro

主に、以下のURLを参考にしています。
http://qiita.com/naoki85/items/c7660d70347e9e70b201

**Comment by saitos01** [comment]
「phptraining」への変更確認いたしました。ばっちりですね。

一枚目の画像の確認ができておりませんが
https://www.evernote.com/l/ARuAJXQUestI46E2yPNdXd_poRpGSk4CIhQ

他の画像をみる限り、流れもちゃんとできていると思います。
ブランチを切り分けてのPushの練習もされているようでGoodです。

補足をするとすると四枚目のPullRequsetのボタンを押したあとの先のページで「Merge Pull Request」を押すとブランチの変更内容がmasterに反映(merge)され(masterが最新のものになり)ます。

https://www.evernote.com/l/ARvUGyrOscBJzpdjMMZOq19TisPwpwTRZro

**Comment by yousuketanaka** [comment]
「Merge Pull Request」の件、承知しました。一度試してみます。

**Comment by yousuketanaka** [comment]
今回、新たにデータをプッシュして「Merge Pull Request」を押す機会がありました。教えていただいた通り、実行することができました。また、詳細は以下のURLでも確認できました。
http://qiita.com/samurairunner/items/7442521bce2d6ac9330b

**Comment by saitos01** [comment]
いいですね。Pull Request できています。課題終了されたのでこのIssueはCloseしたいと思います。
