### ISSUE TITLE
PHPのプログラミングからSQLを使ってデータを操作する。

### ISSUE THREAD

**Issue by saitos01** [yousuketanaka/phptraining#8]
こちらもまずは調査タスクになります。

https://github.com/yousuketanaka/phptraining/issues/5

のissueでは「PHPMyadminから直接SQL文を入れることでデータをINSERTしました。」

このissueでは

「PHPからMySQLにデータをINSERTする」 

ということを調べてみましょう。

調べてみると簡単なサンプルコードが手に入るのでそちらを一度試してみるのがいいと思います。

**Comment by saitos01** [comment]
追加として、phpMyAdminからデータのエクスポートというのがあります。

これをすると今作っているデータベースの内容をテキストに出せるので、GitHubにPushして私と共有することができます。

こちらも一度調査してみましょう。

**Comment by yousuketanaka** [comment]
承知しました。現在、別の業務を行っていますが、午後には取り組みが開始できると思います。

**Comment by saitos01** [comment]
お願いいたします。
連絡ありがとうございます。
Issueは先の内容が今後随時追加されていくかと思いますが
田中さんご自身のペースで進めてくださいね。

**Comment by yousuketanaka** [comment]
> 「PHPからMySQLにデータをINSERTする」ということを調べてみましょう。

非常に多くの学習ポイントが詰まったテーマだと思います。また、これまで掲示板を作成する上で、最も理解に苦しめられたところになります。まず概念整理が必要と感じています。

ここはこれまで私の理解が非常に遅れているところで、一つ一つ確認しながら進めさせてください。
もし、理解に誤り、漏れがあればご指摘ください。

まず不明点は以下の通りです。

◽️確認点/不明点
①PDO::ATTR_EMULATE_PREPARESの意味は何か?
②静的プレースホルダと動的プレースホルダの違いが正確に理解できない。調べるヒントを頂きたい。
③PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTIONは調べると、「例外を表示する」とあるが、なぜここでこの表記が必要なのかがわからない。調べるヒントを頂きたい。
④どのような時に、$stmt = $dbh->query($sql);を使い、どのような時に、$stmt = $dbh->prepare($sql);を使うのかが理解できません。
⑤どのような時に$stmt->bindParam(':@@', $@@, PDO::PARAM_STR);と
$stmt->bindValue(':@@e', $@@, PDO::PARAM_INT);を使うのかがわかりません。調べると、両方を使っていない例もあれば、一方を使っている例もあります。

---

以下、私の学習の流れに沿って不明点を記しています。いろんな要素が絡み合っていてうまくまとめきれていないというのが正直なところです。

◽️PHPからデータベースへ接続する時は、以下のプロセスをたどる認識でいます。
①DBへの接続
②SQL文の準備
③SQL文の実行
④SQL文の結果の取り出し

この一連のプロセスにおいて、同時にセキュリティ対策(SQLインジェクション対策)を行います。
A.文字エンコーディングを指定する
B.静的プレースホルダを用いる
C.バインド時に型を指定する

---

◽️DBへの接続（①）

DBへの接続はPDOを用います。PDOとは、同じ書き方で全部のほぼ全てのデータベースに対応するという宣言のことと理解しています。

使い方は以下の通り。1と2は書き方が違うだけで意味は同じ。
だが、2の$dbn、$user、$passを別のファイルにする方がセキュリティ上安全。
new PDOとは決まり文句と考える。

1.$dbh = new PDO(('mysql:host=ホスト名; dbname=DB名; charset=utf8'),'ユーザー名','パスワード');
  //ここでAを満たす。

   $dbh->setAttribute(PDO::ATTR_EMULATE_PREPARES,false);
   $dbh->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

2.$dbn = "mysql:host=localhost; dbname=recipes; charset=utf8"; //ここでAを満たす。
   $user = "@@@";
   $pass = "@@@";      //これらは別のファイルへ

   $dbh = new PDO( $dbn, $user, $pass);
   $dbh->setAttribute(PDO::ATTR_EMULATE_PREPARES,false);
   $dbh->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

3.setAttribute(PDO::ATTR_EMULATE_PREPARES,false);
PDO::setAttributeは属性を設定するもの。
PDO::ATTR_EMULATE_PREPARESについて
🔹理解できたこと
SQLインジェクション対策において重要な命令である。（役割）
従って、PDO::ATTR_EMULATE_PREPARESを「false」にするのが慣例。

🔹理解できないこと
結局、どのような命令を出しているのか理解できない。要はどういうことか?（意味）
また調べる過程で静的プレースホルダと動的プレースホルダが出てきたが、この意味の違いを
以下のように理解した。ただし、深くは理解していない。
静的プレースホルダ・・・データベースに入れる値が決まっている。
動的プレースホルダ・・・データベースに入れる値が随時変わる。

マニュアルには、PDO::ATTR_EMULATE_PREPARESの記載はなく、
以下4つを参照したが、理解が深まらない。

(http://php.net/manual/ja/pdo.setattribute.php)
(http://qiita.com/tabo_purify/items/d1166236f3b03c7be60d)
(http://qiita.com/stk2k/items/c46cc921a4f7b6e4bab2)
(http://qiita.com/7968/items/7ddd59b94eb5a4fb6eaf)

🔹$dbh->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
DB接続に失敗したときは例外を表示する？

http://qiita.com/yukix/items/7ac1e5aca91b8794f804
http://www.php.net/manual/ja/pdo.error-handling.php

---

◽️sql文の準備（②）

$sql = "INSERT INTO inqiries( name, furigana, prefecture, address, contact, gender, message) VALUES(?, ?, ?, ?, ?, ?, ?)";
$stmt = $dbh->query($sql);

$stmt = $pdo->query('SELECT \* FROM people');

🔹$stmt = $dbh->prepare($sql);との違いは何か？

どのような時に、$stmt = $dbh->query($sql);を使い、
どのような時に、$stmt = $dbh->prepare($sql);を使うのかが理解できません。

🔹bindParamとbindValueの役割

なぜこの二つを使うのか？どのような状況で使うのかが理解できない。
$stmt->bindParam(':name', $name, PDO::PARAM_STR);
$stmt->bindValue(':value', $value, PDO::PARAM_INT);

---

③SQL文の実行
$stmt ->execute()

---

④SQL文の結果の取り出し
$result = $stmt->fetchAll(PDO::FETCH_ASSOC);

**Comment by saitos01** [comment]
> ◽️確認点/不明点 ①PDO::ATTR_EMULATE_PREPARESの意味は何か? ②静的プレースホルダと動的プレースホルダの違いが正確に理解できない。調べるヒントを頂きたい。

①、②はあわせて学習すると効率的です。
- 「静的プレースホルダ 動的プレースホルダ」で検索してみましょう。
- 次に「エミュレート」を簡単に調べてみましょう。
- 「PDO::ATTR_EMULATE_PREPARES」をture、falseは動的、静的プレースホルダのどちらに当てはまるか考えてみましょう。

すでに色々調べられているようなので、もし詰まるようでしたら（本当は時と場合によりけりなのですが）今はPDO::ATTR_EMULATE_PREPARESはfalseを使うという認識で大丈夫です。
静的プレースホルダと動的プレースホルダの違いも現段階では、どちらも「プレースホルダ」という仕組みを利用しているのだという認識でOKです。

> ③PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTIONは調べると、「例外を表示する」とあるが、なぜここでこの表記が必要なのかがわからない。調べるヒントを頂きたい。
- 「PDO::ATTR_ERRMODEをPDO::ERRMODE_EXCEPTIONで設定している」ということはご理解いただけていると思います。ではこの設定をしなかった時(デフォルトでのERRMODEが)
  どのような状態なのかを意識して調べてみると良いでしょう。もし、「例外を表示する意味」というところで詰まるのでしたら一旦置いておき、先々の学習で補足していきましょう。

> ④どのような時に、$stmt = $dbh->query($sql);を使い、どのような時に、$stmt = $dbh->prepare($sql);を使うのかが理解できません。 
- 「プレースホルダ」を使うと「SQLインジェクション対策」になるということはおおまかに理解されているかと思われます。
-  prepareとqueryどちらがプレースホルダを扱う時に使うものかということを意識すると理解が簡単かもしれません。
  後ほど扱うテーマですので今はとりあえず「prepare」を使うという認識でも大丈夫です。

> 以下、私の学習の流れに沿って不明点を記しています。いろんな要素が絡み合っていてうまくまとめきれていないというのが正直なところです。
> ◽️PHPからデータベースへ接続する時は、以下のプロセスをたどる認識でいます。 ①DBへの接続 ②SQL文の準備 ③SQL文の実行 ④SQL文の結果の取り出し
> この一連のプロセスにおいて、同時にセキュリティ対策(SQLインジェクション対策)を行います。 A.文字エンコーディングを指定する B.静的プレースホルダを用いる C.バインド時に型を指定する

こちらの流れと確認点/不明点の組み合わせほぼあっております。
気になる点としては「query」の位置でしょうか。こちらは「確認点/不明点の④」での解答次第で位置が変わると思います。また、PDO::setAttributeは「属性」よりも「接続オプション」のほうがわかりやすいでしょうか。

**Comment by saitos01** [comment]
確認点/不明点でヒントを与えさせていただきましたが、そうであっても「理解できる部分」と「理解に詰まる部分」はあると思います。
まずは「理解できる部分」を今後のIssueで試しつつ進めていき、後々に「理解に詰まる部分」を埋めていきましょう。
進めていくことによって今は詰まる部分もあっさり腹に落ちる時はよくあります。

プログラミングの学習を進めていく上で
①. 「今はっきり理解しなければいけないこと」と
②. 「今はある程度の理解で止めておき、慣習的、一般的なことだけ覚えておけば使えるし大丈夫」
ということを見極めること(取捨選択すること)も必要になってきます。

確認点/不明点で「今は~と理解しておけばOK」のように書いたものは、もし今の段階で調べて深くは理解できなかったとしても、②の分類にあてはまる事柄になります。これはプログラミングの学習の初期~中期では多く存在します。

特に今回の田中さんの確認点/不明点は、複合的な理解が必要になる(複数のピースが合わさってはじめて理解ができる)箇所だと思います。
進めていきつつ「今はっきり理解しなければいけないこと」への理解を深めていく（手持ちのピースが増えていく）とピースが合わさって納得できる箇所になると思います。

田中さんの「今書いているコードの意味をはっきりさせたいという意識」はプログラマーとして正しい考え方、方向性だと思いますし、長所なのではないかと思います。
反面今後「今書いているコードの意味をはっきりさせなければ進むことができない」という壁にぶつかるかもしれません (私がそうなりました笑)。
そのような時は上記の学習を進める上での「見極めること(取捨選択すること)」を思い出してみてくださいませ。きっとお役に立つのではないかと思います。

**Comment by yousuketanaka** [comment]
回答非常に助かっています。とりあえず、今調べるように指示いただいたところを纏めて、こちらで発表していきます。

**Comment by saitos01** [comment]
ありがたいお言葉、感謝いたします。よろしくお願いいたします。

**Comment by yousuketanaka** [comment]
> 「静的プレースホルダ 動的プレースホルダ」で検索してみましょう。

まずはプレースホルダの意味となります。
「SQL文の準備」において、以下のような指示を出したとします。

$sql = "insert into recipe (name, furigana, email, prefecture, address, contact, gender, message) values(?, ?, ?, ?, ?, ?, ?)";

この「?」をプレースホルダという。正確には、疑問符プレースホルダという。

このように、SQL中に、後に値を埋め込む場所に「?」などの特別な文字列（これをプレースホルダと言う)を置き、一時的にデータが入る場所を確保している。そして、ここに埋め込む値はSQL本体と切り離す。この実際の値を割り当てることを「バインドする」と呼ぶ。また、プレースホルダのことを「バインド変数」と呼ぶこともある。

これらを切り離すことで、SQLサーバは、パラメータの内容はあくまでも「値」として解釈し、たとえその値にSQLとして解釈できる文字列が記述されていても、それをSQLとして実行することはしない、という仕組みである。このプレースホルダを設定することでSQLインジェクション対策になる。

そして、切り離された値は、$stmt->bindValue(何番目の?か, 当てはめる変数, 値の型);で指定する。
従って、当てはめる変数を置くためには、例えば以下のように、予め変数を指定する必要がある。
$name = $_POST['name'];
$furigana = $_POST['furigana'];
$prefecture =$_POST['prefecture'];
$address = $_POST['address'];
$contact = $_POST['contact'];
$gender = $_POST['geder'];
$message = $_POST['message'];

結果、以下のURLのようにPHPからデータベースを操作し、INSERT文の命令を出すことができる。

https://www.evernote.com/l/ARuSRAtZwV5K5bK8swm09LKxq-vpl30VRH8

次に、「静的プレースホルダ 動的プレースホルダ」を調べます。

**Comment by yousuketanaka** [comment]
「静的プレースホルダ 動的プレースホルダ」の理解は、SQLインジェクション対策の文脈で理解する方がより理解しやすかった。

◽️SQLインジェクションに対する根本的な解決は、以下の3点がある。

① 前提条件的な対策
②バインド機構(バインドメカニズム)」の使用、
③バインド機構で実装できない場合は、「エスケープ処理(別の文字列への変換)」

---

① 前提条件的な対策
前提条件的な対策として、設計時に以下の4点を行う。

1.「開発用のエラーメッセージをブラウザに出さない」
   ⇨開発時のデバッグではエラーメッセージは有益だが、本番稼働時にも同じ状態のままで放置する
　　と、攻撃者にとってSQLインジェクションの攻撃状況を確認するのに有益な情報源を与えて
　　しまう。

> ⭕️これを根拠に、try〜catch構文が使用されているのでしょうか?

2.「データベースの権限を正しく設定する」
　⇨機能の範囲ごとに、データベースの権限を割り当てたユーザーを作成し、そのユーザーを使用して
　　アクセスすべきである。

3.「入力パラメタのチェック」
　⇨入力項目ごとに決められたチェック処理を行うようにする。例えば郵便番号の場合は、
　「123-4567」の形式のみを有効とする、あるいは都道府県を「01～48」のコードで表している
　  場合は、「01～48」の文字列のみを有効とするなど。

4.「日本語の誤認識を防ぐ」
    ⇨日本語などのマルチバイトに対する処理がきちんと行われている必要がある。

> ⭕️ここはよくわからない。マルチバイトに対する処理がなぜSQLインジェクション対策となるのか?

---

🔹バインド機構
バインド機構とは、あらかじめSQL文のひな型を用意し、後から変動個所（プレースホルダ）に実際の値（バインド値）を割り当ててSQL文を生成するデータベースの機能のことを言う。プレースホルダによる組み立ては、バインドをいつ行うのかによって2種類に分けることができる。

①静的プレースホルダとは?

プレースホルダのままの SQL 文をデータベースエンジン側にあらかじめ送信して、実行前に、
SQL 文の構文解析などの準備をしておく方式。SQL 実行の段階で、実際のパラメータの値をデータ
ベースエンジン側に送信し、データベースエンジン側がバインド処理する。、このやり方はSQL インジェクションの脆弱性を生じさせない。

②動的プレースホルダとは?

パラメータのバインド処理をデータベースエンジン側で行うのではなく、アプリケーション側のライブラリ内で実行する方式。

以下の説明がもっともわかりやすかった。
https://www.ipa.go.jp/files/000017320.pdf

---

🔹エスケープ処理とは?
SQLインジェクションのために挿入された文字列を攻撃が成功しないように文字列の置き換えを行う処理を言う。例えば、「’」を「’’」に変換し、「\」を「\」に変換するなどの別の文字列への変換処理を指す。

入力直後にエスケープ処理を行うと、SQL文を生成する直前に別の文字列操作が行われた場合、SQLインジェクションが成功する文字列が完成してしまう可能性があるため、エスケープ処理は、SQL文を生成する直前に実施するのが定石である。

どのような命令文の型をとるのかは後日学習する予定。

**Comment by yousuketanaka** [comment]
> エミュレートとは?

この言葉をわかりやすい言葉で説明しているサイトを見つけることができませんでした。

🔹理解したこと
【役割】
①PDO::ATTR_EMULATE_PREPARES => True    ⇨動的プレースホルダの方式を採用する。
　プリペアドステートメントのエミュレーションを有効にする。

②PDO::ATTR_EMULATE_PREPARES => False  ⇨静的プレースホルダの方式を採用する。従って、SQLインジェクションが絶対に起こらない。
プリペアドステートメントのエミュレーションを無効にする。

🔹PreparedStatementとは?
①調べる過程で頻繁に使われた単語でしたので調べてみましたが、いまいち理解できません。マニュアルには、「実行したい SQL をコンパイルした 一種のテンプレートのようなものです。」とあります。さらに調べると、コンパイルとは「プログラミング言語で記述されたプログラムのソースコードをコンピューターで実行可能な形式に変換すること。」とあり、要は、実行したいSQLを実行可能な状態にするための決まった形」と理解すればよいでしょうか?

②仮にそうだとすれば、これからDBに接続して、データを追加/修正/削除したいと考えている時に、SQLを実行可能な状態にしないという選択はないと思うのですが、なぜ以下のPDO::ATTR_EMULATE_PREPARES => False
が存在しているのかがわかりません。従って、上記での意味ではないのではないかと懐疑的です。

③明確な記述は見つかりませんでしたが、幾つかのサイトの記述から考えると、PreparedStatementとは以下の2つを合わせたものをさしているように思います。PreparedStatementと言われると、以下の2つを指していると覚えてしまってもよいのでしょうか？

PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
PDO::ATTR_EMULATE_PREPARES => false,

④また、このPreparedStatementは、DBへの接続の際、以下のPDOクラスと一緒に使われますが、 DB接続時のパターンとして考えてもよいのでしょうか？
$dbh = new PDO(('mysql:host=ホスト名; dbname=DB名; charset=utf8'),'ユーザー名','パスワード');

**Comment by yousuketanaka** [comment]
🔹PreparedStatementとは?（続き）

参考URL: http://www.atmarkit.co.jp/ait/articles/1006/25/news093.html
http://runble1.com/security-pdo/

上記のURLを見ると、私が当初考えていたよりも更に狭い意味でPreparedStatementが使われています。
このサイトに登場する高木氏は、「PreparedStatement　= 　静的プレイスホルダ」と言い切っています。静的プレイスホルダは、「プレースホルダのままの SQL 文をデータベースエンジン側にあらかじめ送信して、実行前に、SQL 文の構文解析などの準備をしておく方式」ですので、PreparedStatementを直訳しても理解しやすいです。

プリペアドステートメントを利用してクエリを実行するには以下の流れで実行する。

PDOオブジェクトの作成
↓
prepareメソッドでSQL文をセット
↓
bindValue or bindParamでパラメータに値をセット
↓
executeメソッドでクエリを実行
↓
fetch or fetchAllメソッドで結果を配列で取得

**Comment by yousuketanaka** [comment]
「PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION」とは?

理解したこと
🔹PDO::ATTR_ERRMODE　⇨  接続中にエラーが発生した場合、それをどのように通知するかを決める。

理解できないこと/わからないこと

以下を理解するために、どのような検索方法がありますでしょうか?
🔹PDO::ERRMODE_EXCEPTION　⇨　「例外をスローさせる。」とあるが、エラーの通知方法としてエラーの例外を表示させることに、どんな意味があるのか？
🔹結局、上記2つを合わせた「PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION」は何を命令しているのか?あるいはどういう役割を果たすのか? どうも報告方法と例外が結びつかない。
🔹try -catch構文のcatch部分との関連性はあるのか?

仰るように、ここに拘るよりも、こういうものだとして先に進む方が良いのかもしれません。
ただ、ここを通過する場合、「今は~と理解しておけばOK」でいえば、ここは何になりますでしょうか？ここはエラーの通知方法を定めていると一旦理解しておけば良いのでしょうか？

**Comment by saitos01** [comment]
プレースホルダ、静的プレースホルダ、動的プレースホルダの意味よさそうですね。

SQLインジェクション対策の理解もおおまかにされているので、細かい点は進めつつ詰めていきましょう。

エミュレート(エミュレーション)について、

http://bit.ly/29EPJaJ

によると

ある装置やソフトウェア、システムの挙動を別のソフトウェアなどによって模倣し、代替として動作させること。

「ある装置やソフトウェア、システム」= 今回でいうとデータベースエンジン側 ≒ Mysql
「別のソフトウェア」= 今回でいうとアプリケーション側 ≒ PHP

というとわかりやすいでしょうか。

PreparedStatementとは?

田中さんに頂いたPDFにも
https://www.ipa.go.jp/files/000017320.pdf

「PreparedStatement　= 　静的プレイスホルダ」のように書いてありますしその理解で良いと思います。

「PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION」とは?

> 仰るように、ここに拘るよりも、こういうものだとして先に進む方が良いのかもしれません。ただ、ここを通過する場合、「今は~と理解しておけばOK」でいえば、ここは何になりますでしょうか？ここはエラーの通知方法を定めていると一旦理解しておけば良いのでしょうか？

良い選択だと思います。
PDO::ATTR_ERRMODE　は　「エラーの通知方法を定めている」
PDO::ERRMODE_EXCEPTION　は「エラー時に例外を発生させる」、デフォルトだと必要なエラー情報を例外として投げてくれないので通常のエラーモードはこちらが望ましい。

という理解でOKです。

**Comment by saitos01** [comment]
最後の見極めとても良い判断だと思います。「はっきりさせなければ進めなくなる」という壁にぶつかる前に判断されたのかと思います。

もちろん、田中さんが抱える疑問を潰していきつつ進めていくことも可能ですし、疑問を解消することも大切な考え方だと思っております。
ただ、トレーニング後のことを考えると、今(トレーニング内では)は見極める力をつけて取捨選択していくことが大切だと思っております。
理由としましては、疑問を全て解決して進むことが良いという経験になってしまうと、何かわからない時に常にメンターが必要ということになってしまうかもしれません(ご自身で全て解決できるレベルが必要になります)。

ですので今の段階では「わかる範囲の知識をつなぎながらでも進んでいくこと」が「自分でコードを書いて作りたいサービスを形にする」上では重要になってきます。
進んでいくと今わからないこともわかるようになってくることが多々あります。

今はこれが「~と理解しておけばOK」な知識なのか「はっきり理解しなければならない知識なのか」判断に迷うと思われます。
そのようなときは気軽に聞いてください。
例えば少し調べてみて理解に困ったとき、「今の段階ではこのような理解だけど大丈夫か」というように聞いていただいて構いません。

トレーニング内でその見極めと取捨選択がご自身できるようになってくると自分で課題解決しながら書く力というのが着いてきます。
何度もいって恐縮ですが、田中さんの「わからないことを明らかにする」という意識はとても大切な考え方です。
ただ、まずは取捨選択する力を鍛えていきましょう。

**Comment by yousuketanaka** [comment]
上記、承知しました。では、上記の方法で進めます。

**Comment by yousuketanaka** [comment]
一点確認ですが、

> PDO::ERRMODE_EXCEPTION　は「エラー時に例外を発生させる」、デフォルトだと必要なエラー情報を例外として投げてくれないので通常のエラーモードはこちらが望ましい。

この「例外」という記述が気になります。ここでいう例外とは何でしょうか？何度調べても、この例外という言葉は、さも当たり前のように使われています。

「デフォルトだと必要なエラー情報を表示してくれない」と言われればわかりやすいのですが、この理解であっていますか？

「デフォルトだと必要なエラー情報を表示してくれない」　⇨従って、「エラー表示よって問題箇所が特定できる」、となると意味も役割も明確に理解できます。

この場合、try-catch構文と一緒に使うことで、catch以降でエラー表示をしてくれる、となると更にわかりやすいのですが、そうではないのでしょうか？

**Comment by yousuketanaka** [comment]
bindValue()とbindParam()の違いを調べました。誤りや情報の漏れがありましたら、ご指摘ください。

プレイスホルダに値を割り当てるバインドの方法が2種類あるということ、と理解している。

🔹役割
ともに、SQL 文の中で、 対応するプレースホルダに値をバインドする役割を持つ。

🔹違い
要は、2つの違いは、処理できる能力の違いと理解しています。

①bindValue(); 
 -値と変数を受け取る。
 -すぐに値（変数）を読み込む。（その時点で、バインドされる値が確定する（execute前））

?に入る値の指定方法
bindValue(何番目の?か, 当てはめる変数（数）, 値の型);

値の型については以下を参照
http://php.net/manual/ja/pdo.constants.php

②bindParam();　
 -変数しか受け取らない。
 -execute()が実行された時点で変数を読み込む。executeされるまでは、値を参照しているため、参照
  している変数の中身が変わると、別の値がバインドされる可能性がある。従って、bindParamを
  ループ内で使用すると不具合となる。

従って、「?」を使ったプレイスホルダであれば、bindValue(); を使っておく方が良いと理解しています。

**Comment by yousuketanaka** [comment]
preparedとqueryの使い方の違いについて以下のように理解しています。誤りや情報の漏れがありましたら、ご指摘ください。

🔹値が固定じゃない場合はprepareを使うのが基本。要は、実行するSQL文の中に変数などがある場合はprepareを使用する。

$sql = "SELECT \* FROM data WHERE id = ?";

🔹実行するSQL文が固定されている場合（一回しかSQL文を使用しない場合）はqueryを使用する。
　以下のようなSQL文では、どちらを使っても良い。

$sql = "SELECT \* FROM data";

**Comment by yousuketanaka** [comment]
参考URL:http://qiita.com/7968/items/6f089fec8dde676abb5b
上記のURLを読めば、「例外」の意味がなんとなく理解できました。
やはり、「エラーを表示」と同義と考えていいような気がします。

ここは後日、クラスやインスタンスを学習した時により理解できるのと考えており、一旦は、以下のように理解することにしました。

🔹例外とは?

まず言葉の問題として、例外を知らせることを、「例外を投げる（スローする）」と表現する。
ここで例外とは、「エラー報告（警告表示）」と同義語と理解しています。

🔹このエラー報告は幾つかのステップを踏んで行われる。

①エラー報告を出すことを準備段階で宣言する。
それが、try{}内にある以下の文となる。
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

②エラー報告が出された時に、それを受理する。
catch(Exception $e) で、上記のエラー報告を受け取っている。

③エラー報告を処理して、表示する。
$e->getMessage()がエラー報告を処理して、エラーメッセージを表示する。

やはり、$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);は、
try{} catch{}構文と密接に関係しているようです。

**Comment by yousuketanaka** [comment]
ここから先へ進まなくなりましたのでヒントか方向性を示していただければと思います。
phptraining/task2/form_output.php

🔹わからない点は、以下の通りです。
insert文を指示するはできていると思うのだが、結果をどのように表示させればよいのかわからない。
上記のパスでは、以下2つを試しています。ですが、書き方も含めてどこが誤りなのかがわかりません。
①try-catch構文のtryに記入しているパターン
②<?php ?>の外に書いているパターン

**Comment by saitos01** [comment]
一番上の質問からお答えしていきます。

> この場合、try-catch構文と一緒に使うことで、catch以降でエラー表示をしてくれる、となると更にわかりやすいのですが、そうではないのでしょうか？

あっております。

http://bit.ly/29FnqbX

こちらをみると

> 例外処理（れいがいしょり）とは、プログラムがある処理を実行している途中で、なんらかの異常が発生した場合に、現在の処理を中断（中止）して、別の処理を行うこと。その際に発生した異常のことを例外と呼ぶ。

となっております。例外処理の基本はPHPですとtry-catch構文と理解して良いです。

例外処理の文脈のなかでは エラー  =  例外 でも通じますよ。例外はエラーの部分集合と思って大丈夫です。

こちらも実際に例外処理を何回か書く経験をされると納得できるものに入ると思います。

**Comment by saitos01** [comment]
bindValue()とbindParam()の違いに関しての理解はあっております。

**Comment by saitos01** [comment]
preparedとqueryの使い方に関しても理解であっております。

**Comment by yousuketanaka** [comment]
上記承知しました。不明確だった理解が固まって安心感を感じています。

**Comment by saitos01** [comment]
> $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);は、
> try{} catch{}構文と密接に関係しているようです。

こちらもあっていますー。

PHPのプログラミングからSQLを使ってデータを操作する流れの中での
「エラー報告」のステップとしてあっております。

**Comment by saitos01** [comment]
https://github.com/yousuketanaka/phptraining/blob/master/task2/form_output.php

こちらまだおおまかにみた感じですが、

Formで受け取った値をPHPからINSERTされているということですね。
ここで質問なのですが

1、 INSERTされたものはどこに入りますでしょうか。
2、1の答えの中にデータはちゃんと入っていますでしょうか。
3、2で入っているデータをPHPでとってくるにはどうすれば良いでしょうか。

3のヒントーPHPでデータを挿入するにはSQL文のINSERTをPHP内で使いましたね。SQL文でデータを取得・検索するには何を使いましたでしょうか。

とりあえずは以上のヒントになりますがいかがでしょうか。
まずはPHPでデータを取得・検索してくるというところまで進めてみましょう。

次に取得したデータを画面に表示することになります。こちらも調べてみながら進めてみましょう。

**Comment by yousuketanaka** [comment]
回答ありがとうございます。考えてみます。
1は最終的にphpmyadminに値が格納されなければならないと認識しています。
2を特に調べたいのですが、どのようなキーワードでもって調べればよいでしょうか？実は、掲示板を作る時もこのステップでつまづいて先に進めなかった経緯がありました。

**Comment by saitos01** [comment]
1は最終的にphpMyAdminに値が格納されなければならないと認識しています。

こちらであっております。

2 はつまり、phpmyadminの中にデータは入っているかということになるのですがいかがでしょうか。

phpMyAdminにデータをSQLでINSERTした場合、どのように確認しましたでしょうか。

3、2で入っているデータをPHPでとってくるにはどうすれば良いでしょうか。に関してはこのIssueの範囲外でしたね。

https://github.com/yousuketanaka/phptraining/issues/10

こちらのIssueの範囲になります。申し訳ありません。

Issue8内ではデータベースに値が格納されるところまで確認できればOKです。

**Comment by yousuketanaka** [comment]
回答ありがとうございます。本日はこのタスクの完了を目指します。

**Comment by saitos01** [comment]
phpMyAdmin内にデータが入っていないということでしたら、また連絡くださいませ。

Issue8終わりましたら

#10

に取り掛かりましょう。

**Comment by yousuketanaka** [comment]
承知しました。

**Comment by yousuketanaka** [comment]
>phpMyAdminにデータをSQLでINSERTした場合、どのように確認しましたでしょうか。

こちら助言を元に、以下のように試しましたがうまくいきませんでしたので再度、ご助言をお願いします。

①insert into のSQL文を実行し、DBに記入データを登録することはできました。（insert.php）
②次に、insert.phpからheader('Location:form_select.php');を置くことで、select.phpに遷移し、
　select.phpでselect  fromのSQL文を実行させることでDBの情報を表示させようとしました。

しかし、結果はselect.phpが開かなくなりました。確認したいこととして、
①上記の方向性は合っているのか？特に、select.phpで呼び出す部分。
②合っている場合、上記のようにDB情報の確認のために、2つのファイルを作成するべきか？

よろしくお願いします。

**Comment by yousuketanaka** [comment]
> PHPからMySQLにデータをINSERTする

ようやく、PHPからMysqlにデンターをinsertすることができましたので
コードのご確認をお願いします。

🔹できたこと
①phpmyadminへのデータの蓄積(insert文)
②DBへアクセスし、データの取得(select文)

データは、以下にプッシュしております。
phptraining/task2/

ご確認よろしくお願いいたします。

**Comment by saitos01** [comment]
おお、できていますね。ご自身でエラーを解決されて実装されたのがとても良い形だと思います。

何点かコードに関してコメントさせていただきました。ただこのIssueは、

①phpmyadminへのデータの蓄積(insert文)
②DBへアクセスし、データの取得(select文)

が動作するところまでが目標ですので、今後書かれるコードで反映されれば良いと思っています(もし気になるようでしたら修正もちろんOKです)。

https://github.com/yousuketanaka/phptraining/commit/27d0234d0372a6d5f5e00b59d9b86a755ef34b54
https://github.com/yousuketanaka/phptraining/commit/819144472c9a6302564f41fa151a57a6935d93b8

**Comment by saitos01** [comment]
あとは、データベースの都道府県の型をvarcharにしましょう(今Formから「東京都」という文字列が送られてきているので)。電話番号もvarcharにしましょう(tinyintですと127までか入らないため、他数値型でも先頭の0が削れてしまいます)。

上記指摘もれでした、申し訳ありません。

https://www.evernote.com/shard/s283/sh/4833efe5-76db-44eb-80b0-3051035e7b83/c1f79d5d755bf74f

電話番号カラムについての参考URL

http://sigisi.hatenablog.com/entry/20100829/1283100665

こちらも今後反映されれば良いものです(もし気になるようでしたら修正お願いします。)

**Comment by yousuketanaka** [comment]
> あとは、データベースの都道府県の型をvarcharにしましょう(今Formから「東京都」という文字列が送られてきているので)。電話番号もvarcharにしましょう(tinyintですと127までか入らないため、他数値型でも先頭の0が削れてしまいます)。

こちら見落としておりました。修正完了しております。

**Comment by saitos01** [comment]
確認ありがとうございます。修正完了了解です。

**Comment by saitos01** [comment]
こちらcloseいたします。
