### ISSUE TITLE
掲示板サービスを作成していきましょう。テーブルの作成。

### ISSUE THREAD

**Issue by saitos01** [yousuketanaka/phptraining#9]
掲示板サービスを作成していきましょう。

掲示板サービスに必要なテーブルを作成していきましょう。

まずは、テーブルは1つ(コメントのデータが入るテーブル、テーブル名は決めていただければと思います。)で考えていきましょう。

次にコメントのデータが入るテーブルにはカラムは何が必要かも考えてみましょう。

考えたテーブルとカラムの構造は以下のような形でこのIssueのコメントに書いていただければと思います(テーブル名は複数系英数字で！)。

```
## テーブル名
- カラム名
- カラム名
- カラム名
- カラム名(例: created_at)
```

次にphpMyAdminに掲示板用のデータベース、テーブルを作成しカラムを追加しましょう。

**Comment by yousuketanaka** [comment]
> まずは、テーブルは1つ(コメントのデータが入るテーブル、テーブル名は決めていただければと思います。)で考えていきましょう。
> 
> 次にコメントのデータが入るテーブルにはカラムは何が必要かも考えてみましょう。

上記2点の問いに対して、以下のテーブル/カラムを作成しております。

##boards(テーブル名)
-id
-name
-comment
-created_at

> 次にphpMyAdminに掲示板用のデータベース、テーブルを作成しカラムを追加しましょう。

以下のように作成しています。
※添付のURL上はcomentになっていますが、実際は、commentに修正しています。

https://www.evernote.com/l/ARvUKzrbmv9FQ631WWGLo7qFILOUdwX85Ac

**Comment by saitos01** [comment]
ありがとうございます。
照合順序とカラム名の英数字かもいいですね。

私の例が悪かったのですが、「updated_at」カラムも追加しましょうか。
また、boardsテーブルの「name」カラムの値をUPDATEした時に「created_at」の値はどうなりますでしょうか。

**Comment by yousuketanaka** [comment]
> 「updated_at」カラムも追加しましょうか。

承知しました。これはコメントの「追加」、「修正」、「削除」の「修正」で使うイメージで捉えています。

> boardsテーブルの「name」カラムの値をUPDATEした時に「created_at」の値はどうなりますでしょうか。

試した結果、created_atとupdated_atでは同じデータ型を設定することはできませんでした。そこで、
created_atのデータ型をdatetime型に、updated_atをtimestamp型にすることで解決しました。
ただ、先日、datetime型は、2038年問題があると仰っていたので、datetime型を使用するのは二の足を踏みました。

**Comment by saitos01** [comment]
「修正」で使うイメージであっております。

上で指摘抜けていてすいません。「2038年問題」はtimestamp型ですよー。
https://github.com/yousuketanaka/phptraining/issues/3#issuecomment-230408060

**Comment by yousuketanaka** [comment]
確かに、過去のコメントを確認して、私の勘違いだとわかりました。認識の修正ありがとうございます。

**Comment by saitos01** [comment]
作成されたテーブルの画像か

https://github.com/yousuketanaka/phptraining/issues/8

の以下を使って掲示板サービスのテーブルの情報いただければ幸いです(急ぎではないのでIssue8終わったあとで大丈夫です)。

> 追加として、phpMyAdminからデータのエクスポートというのがあります。
> 
> これをすると今作っているデータベースの内容をテキストに出せるので、GitHubにPushして私と共有 することができます。
> 
> こちらも一度調査してみましょう。

**Comment by yousuketanaka** [comment]
承知しました。しばらくお待ちください。

**Comment by yousuketanaka** [comment]
念のため、2つの方法（画像とsqlデータ）を送ります。ご確認をお願いします。
🔹画像
https://www.evernote.com/l/ARvuKhrsh95A8Z3bdHnJeqtE9COWiGsvWOI

🔹sqlデータ
phptraining/boards/boards.sql

**Comment by saitos01** [comment]
ありがとうございます。承りました。

**Comment by saitos01** [comment]
こちらcloseしたいと思います。
